name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm install --save-dev @babel/plugin-proposal-private-property-in-object
      - run: npm ci
      - run: npm run lint # Запустите линтер перед сборкой, чтобы найти все проблемы
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ORM_SECRET }}
          publish_dir: ./build
